[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = mB+3qKt4npL885a+qAkL3YIsKiX51czaSjZ5BpocplM=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# NL-FREE#2
PublicKey = zcfEQgUoPLK2kvDicsA/4B9F2AI7qfxX5ueDo/Zcjj4=
AllowedIPs = 0.0.0.0/0
Endpoint = 149.36.51.3:51820