[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = YAxS9yEp61R92S0uKZuGnteMmuUlqxFH3EcuxJdkrnw=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# PL-FREE#1
PublicKey = ScCkMvpikYBB3IFtDJC6Xh59pmq4StGlU/JfvALPxUE=
AllowedIPs = 0.0.0.0/0
Endpoint = 149.102.244.97:51820