[Interface]
# Bouncing = 0
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = MPzk+nPfYl1vRecPWROTjHhKudVDvvPo8c0Vy9ZyCng=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# RO-FREE#1
PublicKey = 5qZc9c0rHEKhBXd+NnQ69AJuYjCKqTjt1hM2+UaZDng=
AllowedIPs = 0.0.0.0/0
Endpoint = 149.102.239.225:51820